version: '3'
networks:
  db-network:
    driver: bridge
    internal: true
  http-network:
    driver: bridge
volumes:
  database:
services:
  database:
    image: postgres:12-alpine
    container_name: irlse-database
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - db-network
    ports:
      - '5432:5432'
    restart: on-failure
    environment:
      POSTGRES_HOST: irlse-database
      POSTGRES_PORT: 5432
      POSTGRES_USER: demoAdm
      POSTGRES_PASSWORD: demoPass
      POSTGRES_DB: irlse
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    environment:
      PORT: 3000
      JWT_SECRET: demo1
      JWT_REFRESH_SECRET: demo2
      JWT_EXPIRESIN: 1d
      DATABASE_URL: postgresql://demoAdm:demoPass@irlse-database/irlse?schema=public
    depends_on:
      - database
    container_name: irlse-backend
    networks:
      - db-network
      - http-network
    ports:
      - '3000:3000'
    restart: on-failure
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    depends_on:
      - backend
    container_name: irlse-frontend
    networks:
      - http-network
    ports:
      - '8081:80'
    restart: on-failure
  adminer:
    image: adminer
    ports:
      - '8888:8080'
    networks:
      - db-network
      - http-network

