version: '3'
networks:
  db-network:
    driver: bridge
    internal: true
  http-network:
    driver: bridge
volumes:
  database:
services:
  database:
    image: postgres:12-alpine
    env_file:
      - .env
    container_name: kupipodariday-database
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - db-network
    ports:
      - '5432:5432'
    restart: on-failure
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    env_file:
      - .env
    depends_on:
      - database
    container_name: kupipodariday-backend
    networks:
      - db-network
      - http-network
    ports:
      - '4000:3000'
    restart: on-failure
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    depends_on:
      - backend
    container_name: kupipodariday-frontend
    networks:
      - http-network
    ports:
      - '8081:80'
    restart: on-failure

